export interface Staff {
    store_id: string,
    staff_id: string,
    staff_name: string,
    staff_email: string,
    staff_password: string,
    role: string,
    pin: string,
    created_at: string,
    updated_at: string,
    isDelete: boolean,
}

export interface DriverPartner {
    id: string,
    type: string,
    name: string,
    benefit: string,
}

export const dummyStaffs: Staff[] = [
    {
        store_id: 'BDG01',
        staff_id: "adm001",
        staff_name: "staff satu",
        staff_email: "staff1@email.com",
        staff_password: "staff1",
        role: "admin",
        pin: "000001",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm002",
        staff_name: "staff dua",
        staff_email: "staff2@email.com",
        staff_password: "staff2",
        role: "admin",
        pin: "000002",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm003",
        staff_name: "staff tiga",
        staff_email: "staff3@email.com",
        staff_password: "staff3",
        role: "admin",
        pin: "000003",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm004",
        staff_name: "staff empat",
        staff_email: "staff4@email.com",
        staff_password: "staff4",
        role: "admin",
        pin: "000004",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm005",
        staff_name: "staff lima",
        staff_email: "staff5@email.com",
        staff_password: "staff5",
        role: "admin",
        pin: "000005",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm006",
        staff_name: "staff enam",
        staff_email: "staff6@email.com",
        staff_password: "staff6",
        role: "admin",
        pin: "000006",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm007",
        staff_name: "staff tujuh",
        staff_email: "staff7@email.com",
        staff_password: "staff7",
        role: "admin",
        pin: "000007",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm008",
        staff_name: "staff delapan",
        staff_email: "staff8@email.com",
        staff_password: "staff8",
        role: "admin",
        pin: "000008",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm009",
        staff_name: "staff sembilan",
        staff_email: "staff9@email.com",
        staff_password: "staff9",
        role: "admin",
        pin: "000009",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm010",
        staff_name: "staff sepuluh",
        staff_email: "staff10@email.com",
        staff_password: "staff10",
        role: "admin",
        pin: "000010",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
    {
        store_id: 'BDG01',
        staff_id: "adm011",
        staff_name: "staff sebelas",
        staff_email: "staff11@email.com",
        staff_password: "staff11",
        role: "admin",
        pin: "000011",
        created_at: "2024-1-1",
        updated_at: "2024-1-1",
        isDelete: false,
    },
]

export const dummyDriverPartners: DriverPartner[] = [
    {
        id: "1",
        type: "Online Delivery",
        name: "Gojek",
        benefit: "20",
    },
    {
        id: "2",
        type: "Online Delivery",
        name: "Grab",
        benefit: "20",
    },
    {
        id: "3",
        type: "Online Delivery",
        name: "Shopee",
        benefit: "20",
    }
]